// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:random_coffee/core/hive/hive_adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(CartItemModelAdapter());
    registerAdapter(CartModelAdapter());
    registerAdapter(CategoryModelAdapter());
    registerAdapter(ProductModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(CartItemModelAdapter());
    registerAdapter(CartModelAdapter());
    registerAdapter(CategoryModelAdapter());
    registerAdapter(ProductModelAdapter());
  }
}

